{
 "title": "Logs",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Docker Containers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Grafana",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "{container_name=\"grafana\"}"
    }
   ]
  },
  {
   "title": "Loki",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "{container_name=\"loki\"}"
    }
   ]
  },
  {
   "title": "Node Exporter",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "{container_name=\"node-exporter\"}"
    }
   ]
  },
  {
   "title": "Prometheus",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "{container_name=\"prometheus\"}"
    }
   ]
  },
  {
   "title": "Promtail",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "{container_name=\"promtail\"}"
    }
   ]
  }
 ]
}