global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s
alerting:
  alertmanagers:
    - follow_redirects: true
      enable_http2: true
      scheme: http
      timeout: 10s
      api_version: v2
      static_configs:
        - targets: []
scrape_configs:
  - job_name: prometheus
    honor_timestamps: true
    metrics_path: /metrics
    scheme: http
    follow_redirects: true
    static_configs:
      - targets:
          - localhost:9090
  - job_name: grafana
    honor_timestamps: true
    metrics_path: /metrics
    scheme: http
    follow_redirects: true
    static_configs:
      - targets:
          - grafana:3000
  # Node exporter for system host
  - job_name: node-exporter
    honor_timestamps: true
    metrics_path: /metrics
    scheme: http
    follow_redirects: true
    static_configs:
      - targets:
          - node-exporter:9100
  # KVM Kubernetes master node 1
  - job_name: node-exporter-k8s-ctrl-1
    honor_timestamps: true
    metrics_path: /metrics
    scheme: http
    follow_redirects: true
    static_configs:
      - targets:
          - 192.168.122.89:9100
  # KVM Kubernetes master node 2
  - job_name: node-exporter-k8s-ctrl-2
    honor_timestamps: true
    metrics_path: /metrics
    scheme: http
    follow_redirects: true
    static_configs:
      - targets:
          - 192.168.122.19:9100
  # KVM Kubernetes master node 3
  - job_name: node-exporter-k8s-ctrl-3
    honor_timestamps: true
    metrics_path: /metrics
    scheme: http
    follow_redirects: true
    static_configs:
      - targets:
          - 192.168.122.16:9100
  # KVM Kubernetes worker node 1
  - job_name: node-exporter-k8s-wrk-1
    honor_timestamps: true
    metrics_path: /metrics
    scheme: http
    follow_redirects: true
    static_configs:
      - targets:
          - 192.168.122.192:9100
  # KVM Kubernetes worker node 2
  - job_name: node-exporter-k8s-wrk-2
    honor_timestamps: true
    metrics_path: /metrics
    scheme: http
    follow_redirects: true
    static_configs:
      - targets:
          - 192.168.122.97:9100
  # KVM Kubernetes worker node 3
  - job_name: node-exporter-k8s-wrk-3
    honor_timestamps: true
    metrics_path: /metrics
    scheme: http
    follow_redirects: true
    static_configs:
      - targets:
          - 192.168.122.244:9100
