version: "3.9"

networks:
  bridge-net:
    name: bridge-net
    driver: bridge
    ipam:
      config:
        - subnet: 10.100.0.0/16
          gateway: 10.100.0.254
services:
  node-01:
    container_name: node-01
    image: mbrav/docker-net:0.0.1
    restart: always
    build:
      context: .
      dockerfile: ./container/docker-net/Dockerfile
    command:
      - "--interval"
      - "30"
      - "--count"
      - "5"
      - "ping"
      - "node-01"
    networks:
      bridge-net:
        ipv4_address: 10.100.1.0


  node-02:
    container_name: node-02
    image: mbrav/docker-net:0.0.1
    restart: always
    build:
      context: .
      dockerfile: ./container/docker-net/Dockerfile
    command:
      - "--interval"
      - "30"
      - "--count"
      - "5"
      - "ping"
      - "node-02"
    networks:
      bridge-net:
        ipv4_address: 10.100.2.0
